### ISSUE TITLE
[Error] 로그인 성공시에도 로그인 실패 문구 표시 

### ISSUE THREAD

**Issue by FacerAin** [FacerAin/OSS-Jaksimsamil#4]
로그인 성공시에도 로그인 실패 문구 표시

**Comment by JJuOn** [comment]
개발자 도구로 확인해 본 결과, /api/auth/register에서 409 conflict 에러 발생.  
로그인시에도 /api/auth/register가 동시에 호출됨

**Comment by FacerAin** [comment]
auth redux에서 LOGIN action을 REGISTER action으로 잘못 지정하여 발생한 오류.
해당 부분을 수정함.
